name: first-workflow

on: 
  push:
    branches:
      - master
      
jobs:
  sonarQubeTrigger:
    name: SonarQube Trigger
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@master
    - name: SonarQube Scan
      uses: kitabisa/sonarqube-action@v1.0.0
      with:
        host: ${{ secrets.SONARQUBE_HOST }}
        login: ${{ secrets.SONARQUBE_TOKEN }}
#  build:
#    name: Build
#    runs-on: self-hosted
#    steps:
#    - name: checkout
#      uses: actions/checkout@v2
#    - name: Hello  
#      run: |
#        echo "Hello world from self hosted runner!"
        
#  sample-daast-scan:     
#    name: sample-daast-scan 
#    runs-on: self-hosted
#    steps:
#      - name: ZAP Scan
#        uses: zaproxy/action-full-scan@v0.3.0
#        with:
#          target: 'https://www.zaproxy.org/'
